GET http://localhost:7000/artists

###
POST http://localhost:7000/artists
Content-Type: application/json

{
  "name": "Glass Animals"
}

###
PATCH http://localhost:7000/artists/5a16b64f9ad26c64451a5ea1
Content-Type: application/json

{
  "name": "Glass Animals!"
}

###
DELETE http://localhost:7000/artists/5a16b64f9ad26c64451a5ea1